//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoParser.CLI.UserInterface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NovoParser.CLI.UserInterface.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded {0} {1} due to ADC saturation.
        /// </summary>
        internal static string EventADCExclucionReport {
            get {
                return ResourceManager.GetString("EventADCExclucionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        internal static string EventNamePlural {
            get {
                return ResourceManager.GetString("EventNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        internal static string EventNameSingular {
            get {
                return ResourceManager.GetString("EventNameSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to file: .
        /// </summary>
        internal static string FilePathUserQueryText {
            get {
                return ResourceManager.GetString("FilePathUserQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: [options] [files].
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string JobDoneText {
            get {
                return ResourceManager.GetString("JobDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files specified. Please pass at least one file path as an argument.
        ///See --help for help..
        /// </summary>
        internal static string NoFilesErrorText {
            get {
                return ResourceManager.GetString("NoFilesErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed 
        ///Reason: {0}.
        /// </summary>
        internal static string OperationFailedReport {
            get {
                return ResourceManager.GetString("OperationFailedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string ProcessingIdleText {
            get {
                return ResourceManager.GetString("ProcessingIdleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of program.
        /// </summary>
        internal static string ProgramEndText {
            get {
                return ResourceManager.GetString("ProgramEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOVO-project DRS4 binary file parser/reader.
        /// </summary>
        internal static string ProgramExplainationText {
            get {
                return ResourceManager.GetString("ProgramExplainationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} version {1}.
        /// </summary>
        internal static string ProgramNameVersionReport {
            get {
                return ResourceManager.GetString("ProgramNameVersionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------.
        /// </summary>
        internal static string SeparatorLineText {
            get {
                return ResourceManager.GetString("SeparatorLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread {0} - ID: {1}
        ///{2}.
        /// </summary>
        internal static string ThreadExceptionReport {
            get {
                return ResourceManager.GetString("ThreadExceptionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructing Waveform object... .
        /// </summary>
        internal static string WaveformCreationText {
            get {
                return ResourceManager.GetString("WaveformCreationText", resourceCulture);
            }
        }
    }
}
